### ISSUE TITLE
TypeScript definition fails to build when using "noImplicitAny": false

### ISSUE THREAD

**Issue by mattbishop** [nicdex/eventstore-node#16]
If you set `"noImplicitAny": false` in tsconfig.json, eventstore-node fails with this error:

> tsc

node_modules/eventstore-node/index.d.ts(176,5): error TS7020: Call signature, which lacks return-type annotation, implicitly has an 'any' return type.

**Comment by nicdex** [comment]
Fixed in version 0.0.23.
