### ISSUE TITLE
Can't find `Position`

### ISSUE THREAD

**Issue by mattbishop** [nicdex/eventstore-node#20]
I just updated to 0.0.25 and now I'm getting this error in tsc:

node_modules/eventstore-node/index.d.ts(10,18): error TS2304: Cannot find name 'Position'.

Typescript 2.1.5

If I add an exported Position class in index.d.ts everything is fine.

**Comment by nicdex** [comment]
Testing it right now, but it should be fixed in npm package 0.0.26.

**Comment by mattbishop** [comment]
Fixed in 0.0.26
