### ISSUE TITLE
TcpEndpoint.hostname -> .host == Ouch!

### ISSUE THREAD

**Issue by mattbishop** [nicdex/eventstore-node#21]
I upgraded to 0.0.25 and discovered, the hard way, that 'hostname' had been changed to 'host'.

it would be nicer to log a warning of the name change for a few releases.

**Comment by nicdex** [comment]
Sorry about the headache. This project is still in pre release candidate, breaking changes are bound to happen.

I think that keeping backward compatibility at this point would only slow down the development process.

What I could do is publish a changelog that will contain information about breaking changes and new features.
The complete changes log would be in changelog.md. I would also create one issue on github where I'd post the changes for each new version. This way anyone subscribing to that thread would be notified.
Would that work for you?

**Comment by mattbishop** [comment]
Yes thanks. That would be good.

**Comment by nicdex** [comment]
https://github.com/nicdex/eventstore-node/issues/22
