### ISSUE TITLE
subscribeToAllFrom from stored serialized Position 

### ISSUE THREAD

**Issue by michaelmitchell** [nicdex/eventstore-node#23]
I would like to store the last `currentPosition` serialized in Redis so if my processes crashes it can pick up where it left off,  however `subscribeToAllFrom` takes an instance of `Position` and  there is no direct way to resume at a serialized position because the Position class is not available in the main exported package.

I did manage a work around by importing directly from the src folder instead of the main package but it would be nice to be able to import `Position` directly from the package.

This is my work around
```js
import esClient from 'eventstore-node/src/client';
import { Position } from 'eventstore-node/src/results';

...
conn.subscribeToAllFrom(new Position(60697923, 60697923), ...);
```

But ideally I would like to do this.
```js
import esClient, { Position } from 'eventstore-node';

...
conn.subscribeToAllFrom(new Position(60697923, 60697923), ...);
```

**Comment by nicdex** [comment]
Thanks for the request. 
I will review the API to make sure everything required is exposed.

**Comment by michaelmitchell** [comment]
Cool thanks, everything else seems to be working well though so thanks for your hard work on this!

**Comment by nicdex** [comment]
Position is now exposed in package version 0.0.27
