### ISSUE TITLE
am I crazy? npm i is installing folder but nothing in them!

### ISSUE THREAD

**Issue by reharik** [nicdex/eventstore-node#24]
I'm on node 7.7.2 I've tried both yarn and npm when I install eventstore-node I get 
docs
lib
src
all empty folders
I strongly suspect this is not to do with your repo but all my other deps are coming through with the nested files.

**Comment by nicdex** [comment]
Yes the lib folder is empty, unsure why.
Not pointing finger, but I used yarn publish for the first time for v0.0.28.
I published 0.0.29 using npm publish and this time everything is there.
Sorry for the issue.

**Comment by reharik** [comment]
Oh thank you jesus.  omg.  I thought I was loosing my mind.  more so than
usual.
thx.
r
