### ISSUE TITLE
originalPosition

### ISSUE THREAD

**Issue by reharik** [nicdex/eventstore-node#25]
Hi, my events seem to be coming over with originalPosition set to null.  I put a log inside of the eventstore-node code and that is what's comming into the liveQueue ( I think that's what it was ).  there is an event number, but the originalPosition is comprised of two numbers, the event number and whatever the number is after a garbage collection.  It seems like your system knows about it because it's got a property for it but it's null.
I can keep digging and try and find out more, but if you know anything about this that would be great.
Thanks,
r

**Comment by nicdex** [comment]
I'll that a look, make sure there's no bug. 
If you're using linked event in your stream, you have to set resolveLinkTos to true, otherwise originalPosition and originalEvent will be null.

**Comment by reharik** [comment]
well, I think I have linkedEvent set as true, but I'm not actually using them.  maybe that's screwing it up.

**Comment by nicdex** [comment]
Which methods are you using that returns originalPosition null. I want to add tests on it.

**Comment by reharik** [comment]
subscribeToStreamFrom

**Comment by nicdex** [comment]
What is happening when you do a subscribeToStreamFrom: Client does a readStreamEventsForward then starts a subscription for the upcoming events.

Events returned from any type of read (readEvent, readStreamEventsForward, readAllEventsForward and their backward versions) have originalPosition set to null.

This is why non-live events coming from any subscribeFrom will have originalPosition set to null, but live events will have a non-null originalPosition.

I've confirmed this behavior is from the original .Net Client.
