### ISSUE TITLE
tslint error

### ISSUE THREAD

**Issue by mattbishop** [nicdex/eventstore-node#30]
Error at /Users/mbishop/Projects/cookies/node_modules/eventstore-node/index.d.ts:23:12: 'create', which lacks return-type annotation, implicitly has an 'any' return type.

version 0.0.30

**Comment by nicdex** [comment]
Hi @mattbishop I haven't done any changes to the API in recent releases. 
My validation using tsc still passes. 
Is is possible you updated to a newer version of TypeScript or maybe you typescript (tslint) config is stricter than the default one?

**Comment by mattbishop** [comment]
tsc passes fine, but tslint complains. `create()` just needs an explicit return type of `PersistentSubscriptionSettings`.
