### ISSUE TITLE
Optional fields in TypeScript definitions

### ISSUE THREAD

**Issue by aikoven** [nicdex/eventstore-node#32]
`ResolvedEvent` interface has optional `event` and `originalEvent`, but looking at the code and Protobuf messages it seems these fields are always present. 

Please correct me if I'm wrong. This leads to a problem when using TypeScript with `strictNullChecks` in which case the compiler doesn't let you access subfields unless you first check that the field value is not `null` or `undefined`.

**Comment by nicdex** [comment]
EventStore uses the protocol buffer version 2 which has the confusing required and optional fields. Required in proto2 doesn't mean that the field can't be null, it means that the field will be present in the protocol data.

This code is ported directly from the C# code, as you can see here https://github.com/EventStore/EventStore/blob/release-v4.0.1/src/EventStore.ClientAPI/ResolvedEvent.cs
It is pretty clear that the Event and by extension the OriginalEvent property can be null (any object reference in C# can be null, also constructor has clear set to null in certain use case).

I have yet to see a use case where that happens, but I'm reticent to set that value to non-nullable if it's not in the original client code. Maybe open a ticket with them, to ask why the Event value is nullable.

**Comment by aikoven** [comment]
You are right, it seems that it can happen to be `null`.

Thanks for your work!
